### ISSUE TITLE
请问如果我想应用于组件化开发，如何解耦呢？

### ISSUE THREAD

**Issue by ReverseScale** [seanxux/Navigator#1]
我想在 pod 中自动生成 router 代码在模块中，但是自动生成的代码和模版，视图代码不能分离，我会继续探索，同时向大佬寻求思路。

**Comment by seanxux** [comment]
暂时跨模块需要通过url scheme来实现的。
是否可以参考Moya的MultiTarget类似的思路来再做一层封装，来实现跨模块调用

**Comment by ReverseScale** [comment]
好滴，我去看一下 MultiTarget 的实现好不好做到模块内部自动化生成路由代码。
